describe("Assignment-04", () => {
  it("tests Assignment-04", () => {
    cy.viewport(1136, 898);
    cy.visit("https://comp229-assignment2-1.onrender.com/");
    cy.get("li:nth-of-type(3) > a").click();
    cy.get("#signup-firstname").click();
    cy.get("#signup-firstname").type("Bruce");
    cy.get("#signup-lastname").click();
    cy.get("#signup-lastname").type("Wanye");
    cy.get("#signup-email").click();
    cy.get("#signup-email").type("Batman3@gmail.com");
    cy.get("#signup-password").click();
    cy.get("#signup-password").type("Bruce");
    cy.get("button").click();
    cy.get("#signup-password").click();
    cy.get("#signup-password").type("nightwing");
    cy.get("button").click();
    cy.get("#signin-email").click();
    cy.get("#signin-email").type("Batman3@gmail.com");
    cy.get("#signin-password").click();
    cy.get("#signin-password").type("Nightwing");
    cy.get("button").click();
    cy.get("#signin-password").click();
    cy.get("#signin-password").type("nightwing");
    cy.get("button").click();
    cy.get("li:nth-of-type(3) > a").click();
    cy.get("label:nth-of-type(1) > input").click();
    cy.get("label:nth-of-type(1) > input").type("W");
    cy.get("label:nth-of-type(1) > input").type("Wanye IN");
    cy.get("label:nth-of-type(1) > input").type("Wanye Industries");
    cy.get("textarea").click();
    cy.get("textarea").type("BA");
    cy.get("textarea").type("");
    cy.type("{backspace}");
    cy.get("textarea").type("BA");
    cy.get("textarea").type("Batman");
    cy.get("label:nth-of-type(3) > input").click();
    cy.get("label:nth-of-type(3) > input").type("2026-04-11");
    cy.get("div.form-container button").click();
    cy.get("tr:nth-of-type(2) button.btn-edit").click();
    cy.get("tr:nth-of-type(2) button.btn-edit").click();
    cy.get("tr:nth-of-type(2) button.btn-edit").click();
    cy.get("tr:nth-of-type(2) button.btn-edit").dblclick();
    cy.get("tr:nth-of-type(2) button.btn-edit").click();
    cy.get("tr:nth-of-type(1) button.btn-edit").click();
    cy.get("tr:nth-of-type(2) button.btn-edit").click();
    cy.get("tr:nth-of-type(1) button.btn-edit").click();
    cy.get("tr:nth-of-type(2) button.btn-edit").click();
    cy.get("tr:nth-of-type(2) button.btn-edit").click();
    cy.get("label:nth-of-type(1) > input").click();
    cy.get("label:nth-of-type(1) > input").type("W");
    cy.get("label:nth-of-type(1) > input").type("Wanye inc.");
    cy.get("textarea").click();
    cy.get("textarea").type("B");
    cy.get("textarea").type("Batman");
    cy.get("label:nth-of-type(3) > input").click();
    cy.get("label:nth-of-type(3) > input").type("2026-04-12");
    cy.get("button.btn-primary").click();
    cy.get("nav button").click();
  });
});
