describe("Assigment04", () => {
  it("tests Assigment04", () => {
    cy.viewport(1136, 898);
    cy.visit("https://comp229-assignment2-1.onrender.com/");
    cy.get("li:nth-of-type(3) > a").click();
    cy.get("#signup-firstname").click();
    cy.get("#signup-firstname").type("Test1");
    cy.get("#signup-lastname").click();
    cy.get("#signup-lastname").type("US");
    cy.get("#signup-lastname").type("User1");
    cy.get("#signup-email").click();
    cy.get("#signup-email").type("TE");
    cy.get("#signup-email").type("TestU");
    cy.get("#signup-email").type("TestUser1@gmail.com");
    cy.get("#signup-password").click();
    cy.get("#signup-password").type("123456");
    cy.get("button").click();
    cy.get("#signin-email").click();
    cy.get("#signin-email").type("TestUser1@gmail.com");
    cy.get("#signin-password").click();
    cy.get("#signin-password").type("123456");
    cy.get("button").click();
    cy.get("li:nth-of-type(3) > a").click();
    cy.get("label:nth-of-type(1) > input").click();
    cy.get("label:nth-of-type(1) > input").type("A");
    cy.get("label:nth-of-type(1) > input").type("Assigment04");
    cy.get("textarea").click();
    cy.get("textarea").type("S");
    cy.get("textarea").type("");
    cy.get("textarea").type("D");
    cy.get("textarea").type("Demo Test");
    cy.get("label:nth-of-type(3) > input").click();
    cy.get("label:nth-of-type(3) > input").click();
    cy.get("label:nth-of-type(3) > input").type("2026-04-11");
    cy.get("#root > div").click();
    cy.get("div.form-container button").click();
    cy.get("tr:nth-of-type(3) button.btn-edit").click();
    cy.get("label:nth-of-type(1) > input").click();
    cy.get("label:nth-of-type(1) > input").type("A");
    cy.get("label:nth-of-type(1) > input").type("Assigment04");
    cy.get("textarea").click();
    cy.get("label:nth-of-type(1) > input").click();
    cy.get("label:nth-of-type(1) > input").type("Assigment04_update");
    cy.get("textarea").click();
    cy.get("textarea").type("D");
    cy.get("textarea").type("");
    cy.type("{backspace}");
    cy.get("textarea").type("U");
    cy.get("textarea").type("Update D");
    cy.get("textarea").type("Update Demo Test");
    cy.get("label:nth-of-type(3) > input").click();
    cy.get("label:nth-of-type(3) > input").click();
    cy.get("label:nth-of-type(3) > input").type("2026-04-11");
    cy.get("button.btn-primary").click();
    cy.get("nav button").click();
  });
});
